apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: java 
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: java-pod
        image: venugopalpotnuru/eks-build:java
        ports:
        - containerPort: 8080
